[project]
name = "ez-pil"
description = "A Python library built on top of PIL to easily edit/modify images"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
keywords = ["easy-pil", "ez-pil", "pillow", "pil"]
authors = [
    { name = "tibue99" }
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dynamic = ["dependencies", "optional-dependencies", "version"]

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}
version = {attr = "ez_pil.__version__"}

[tool.setuptools.dynamic.optional-dependencies]
docs = {file = "docs/requirements.txt"}

[project.urls]
GitHub = "https://github.com/CookieAppTeam/ez-pil"
Documentation = "https://easy-pil.readthedocs.io/en/latest/"

[build-system]
requires = ["setuptools>=62.6", "wheel"]
build-backend = "setuptools.build_meta"

[tool.commands]
fmt = "python3 -m black . ;python3 -m isort ."
build = "python3 -m setup.py sdist bdist_wheel"
publish = "twine upload dist/* --skip-existing"
